from abc import ABC, abstractmethod
from typing import List, Dict, Any, Optional
import logging
from src.rag.storage import MilvusStorage
from src.rag.nomic_embedding import NomicEmbeddingGenerator

logger = logging.getLogger(__name__)


class BaseDescriptionGenerator(ABC):
    """Abstract base class for description generators."""
    
    def __init__(self, embedding_generator: NomicEmbeddingGenerator, storage: MilvusStorage):
        """
        Initialize the description generator.
        
        Args:
            embedding_generator: Embedding generator for processing content
            storage: Storage system for retrieving content
        """
        self.embedding_generator = embedding_generator
        self.storage = storage
    
    @abstractmethod
    def generate_description(self, content: Dict[str, Any]) -> str:
        """
        Generate a meaningful textual description of the content.
        
        Args:
            content: Content to generate description for
            
        Returns:
            Generated description
        """
        pass


class ContentDescriptionGenerator(BaseDescriptionGenerator):
    """Description generator for creating meaningful textual descriptions of content."""
    
    def __init__(self, embedding_generator: NomicEmbeddingGenerator, storage: MilvusStorage, 
                 llm_model_func=None):
        """
        Initialize the content description generator.
        
        Args:
            embedding_generator: Embedding generator for processing content
            storage: Storage system for retrieving content
            llm_model_func: Function to call the LLM for content analysis
        """
        super().__init__(embedding_generator, storage)
        self.llm_model_func = llm_model_func or self._default_llm_model_func
    
    def generate_description(self, content: Dict[str, Any]) -> str:
        """
        Generate a meaningful textual description of the content.
        
        Args:
            content: Content to generate description for
            
        Returns:
            Generated description
        """
        try:
            # Extract text content
            text_content = content.get("text_content") or content.get("text", "")
            if not text_content:
                logger.warning("No text content found for description generation")
                return "No content available for description."
            
            # Extract metadata
            content_type = content.get("content_type", "content")
            source_file = content.get("source_file", "")
            chapter = content.get("chapter", "")
            page_number = content.get("page_number", 0)
            
            # Generate description using LLM
            description = self._generate_description_with_llm(
                text_content, content_type, source_file, chapter, page_number
            )
            
            return description
        except Exception as e:
            logger.error(f"Error generating description: {e}")
            return "Description not available due to processing error."
    
    def _generate_description_with_llm(self, text_content: str, content_type: str, 
                                     source_file: str, chapter: str, page_number: int) -> str:
        """
        Generate description using the LLM model.
        
        Args:
            text_content: Text content to generate description from
            content_type: Type of content
            source_file: Source file of the content
            chapter: Chapter information
            page_number: Page number
            
        Returns:
            Generated description
        """
        try:
            # Create prompt for description generation
            prompt = f"""
            Create a meaningful textual description of the following {content_type} content 
            from an educational document. The description should summarize the key points 
            and explain the significance of this content for student learning.
            
            Source: {source_file}
            Chapter: {chapter}
            Page: {page_number}
            
            Content:
            {text_content[:2000]}  # Limit content to 2000 characters
            
            Description:
            """
            
            # Call LLM model
            response = self.llm_model_func({
                "type": "text",
                "text": prompt
            })
            
            # Extract description from response
            if isinstance(response, dict):
                return response.get("text", "Description generated by LLM.")
            elif isinstance(response, str):
                return response
            else:
                return "Description generated by LLM."
        except Exception as e:
            logger.error(f"Error generating description with LLM: {e}")
            # Fallback to simple description
            return self._generate_simple_description(text_content, content_type)
    
    def _generate_simple_description(self, text_content: str, content_type: str) -> str:
        """
        Generate a simple description when LLM fails.
        
        Args:
            text_content: Text content to generate description from
            content_type: Type of content
            
        Returns:
            Simple description
        """
        # Extract first sentence or first 100 characters
        sentences = text_content.split(". ")
        if sentences:
            first_sentence = sentences[0]
            if len(first_sentence) > 100:
                first_sentence = first_sentence[:100] + "..."
            return f"This {content_type} content discusses: {first_sentence}"
        else:
            return f"This {content_type} content contains educational material."
    
    def _default_llm_model_func(self, content_item: Dict[str, Any]) -> Dict[str, Any]:
        """
        Default LLM model function for content analysis.
        
        Args:
            content_item: Content item to process
            
        Returns:
            Analysis results
        """
        # This is a placeholder implementation
        # In a real implementation, this would call an actual LLM
        return {
            "text": "This is a meaningful description of the content generated by an LLM.",
            "summary": "Summary from LLM",
            "key_points": ["Point 1", "Point 2"]
        }